### ISSUE TITLE
missing space before closing }} causes formatting problem

### ISSUE THREAD

**Issue by derek73** [textmate/python-django.tmbundle#1]
Thanks for the recent updates to this bundle. I noticed a few regressions and I have no idea how to fix them so I'll post a few issues.

When editing HTML in the "HTML (Django)" format, the color coding is thrown off when a variable does not have an empty space before the closing `}}`. See attached screenshot.

![screen shot 2014-09-03 at 2 32 26 pm](https://cloud.githubusercontent.com/assets/18306/4141902/aba32e20-33b2-11e4-8025-eee1fafb5cbb.png)

**Comment by infininight** [comment]
Fixed by 81d1395950ffb66e689e41863fab9a4f7cc5f30e, thanks for the note.
